Select * from employee 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 0; 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 1; 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 2; 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 3; 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 4; 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 5; 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 6; 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 7; 
Select * from payment; 
Select * from employee; 
Select * from job; 
Select * from salary; 
Select * from department; 
Select * from benefit; 
select employee.*, payment.* from employee join job ON employee.job_id = job.job_id join benefit ON job.benefit_code = benefit.benefit_code join salary ON job.salary_id = salary.salary_id join department ON job.dep_id = department.dep_id join payment ON employee.employee_id = payment.employee_id where employee.employee_id = 41959; 
SELECT * from employee where employee_id = 41959;
select employee.*, job.* from employee join job ON employee.job_id = job.job_id join benefit ON job.benefit_code = benefit.benefit_code join salary ON job.salary_id = salary.salary_id join department ON job.dep_id = department.dep_id join payment ON employee.employee_id = payment.employee_id where employee.employee_id = 41959; 
select employee.*, salary.* from employee join job ON employee.job_id = job.job_id join benefit ON job.benefit_code = benefit.benefit_code join salary ON job.salary_id = salary.salary_id join department ON job.dep_id = department.dep_id join payment ON employee.employee_id = payment.employee_id where employee.employee_id = 41959; 
select employee.*, department.* from employee join job ON employee.job_id = job.job_id join benefit ON job.benefit_code = benefit.benefit_code join salary ON job.salary_id = salary.salary_id join department ON job.dep_id = department.dep_id join payment ON employee.employee_id = payment.employee_id where employee.employee_id = 41959; 
select employee.*, benefit.* from employee join job ON employee.job_id = job.job_id join benefit ON job.benefit_code = benefit.benefit_code join salary ON job.salary_id = salary.salary_id join department ON job.dep_id = department.dep_id join payment ON employee.employee_id = payment.employee_id where employee.employee_id = 41959; 
select benefit_code from job where job_id = 6; 
select benefit_code from job where job_id = 6; 
BEGIN TRANSACTION; 
INSERT INTO employee VALUES (422220, 'Anthony','Ciocco','08-30-1999','test@gmail.com','8325314100','11720 Haben St',6); 
INSERT INTO payment VALUES (422220,2,0,0,0,0.153,0,0); 
COMMIT TRANSACTION; 
SELECT * from employee where employee_id = 422220; 
SELECT * from employee where employee_id = 42222; 
SELECT * from employee where employee_id = 422224; 
SELECT * from employee where employee_id = 422223; 
SELECT * from employee where employee_id = 422223; 
SELECT * from employee where employee_id = 422223; 
SELECT * from employee where employee_id = 422223; 
SELECT * from employee where employee_id = 422222; 
Select * from employee 
select benefit_code from job where job_id = 4; 
select benefit_code from job where job_id = 4; 
BEGIN TRANSACTION; 
INSERT INTO employee VALUES (144517, 'Ant','Ciocco','08301999','bruh@test.com','911','No',4); 
INSERT INTO payment VALUES (144517,0,0,0,0,0.153,0,0); 
COMMIT TRANSACTION; 
Select * from employee 
Select * from employee 
Select * from employee 
SELECT * from employee where employee_id = 422220;
SELECT * from employee where employee_id = 422220;
SELECT * from employee where employee_id = 422220;
SELECT * from employee where employee_id = 422220;
SELECT * from employee where employee_id = 422220;
Select * from employee 
SELECT * from employee where employee_id = 422220;
SELECT * from employee where employee_id = 422222;
Select * from employee 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
DELETE FROM employee WHERE employee_id = 14451; 
DELETE FROM payment WHERE employee_id = 14451; 
DELETE FROM employee WHERE employee_id = 14451; 
DELETE FROM payment WHERE employee_id = 14451; 
DELETE FROM employee WHERE employee_id = 14451123552; 
DELETE FROM payment WHERE employee_id = 14451123552; 
DELETE FROM employee WHERE employee_id = 14451123552; 
DELETE FROM payment WHERE employee_id = 14451123552; 
Select * from employee 
select benefit_code from job where job_id = 4; 
select benefit_code from job where job_id = 4; 
BEGIN TRANSACTION; 
INSERT INTO employee VALUES (144517, 'Ant','Ciocco','08301999','bruh@test.com','911','No',4); 
INSERT INTO payment VALUES (144517,0,0,0,0,0.153,0,0); 
COMMIT TRANSACTION; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
select benefit_code from job where job_id = 4; 
select benefit_code from job where job_id = 4; 
BEGIN TRANSACTION; 
INSERT INTO employee VALUES (144517, 'Ant','Ciocco','08301999','bruh@test.com','911','No',4); 
INSERT INTO payment VALUES (144517,0,0,0,0,0.153,0,0); 
COMMIT TRANSACTION; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
select benefit_code from job where job_id = 4; 
select benefit_code from job where job_id = 4; 
BEGIN TRANSACTION; 
INSERT INTO employee VALUES (144517, 'Ant','Ciocco','08301999','bruh@test.com','911','No',4); 
INSERT INTO payment VALUES (144517,0,0,0,0,0.153,0,0); 
COMMIT TRANSACTION; 
select benefit_code from job where job_id = 4; 
select benefit_code from job where job_id = 4; 
BEGIN TRANSACTION; 
Select * from employee 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
select benefit_code from job where job_id = 4; 
select benefit_code from job where job_id = 4; 
BEGIN TRANSACTION; 
INSERT INTO employee VALUES (144517, 'Ant','Ciocco','08301999','bruh@test.com','911','No',4); 
INSERT INTO payment VALUES (144517,0,0,0,0,0.153,0,0); 
COMMIT TRANSACTION; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
select benefit_code from job where job_id = 4; 
select benefit_code from job where job_id = 4; 
BEGIN TRANSACTION; 
INSERT INTO employee VALUES (144517, 'Ant','Ciocco','08301999','bruh@test.com','911','No',4); 
INSERT INTO payment VALUES (144517,0,0,0,0,0.153,0,0); 
COMMIT TRANSACTION; 
SELECT * from employee where employee_id = 144517; 
DELETE FROM employee WHERE employee_id = 144517; 
DELETE FROM payment WHERE employee_id = 144517; 
SELECT * from employee where employee_id = 144517; 
Select * from employee 
Select * from payment; 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 3; 
select employee.*, benefit.* from employee join job ON employee.job_id = job.job_id join benefit ON job.benefit_code = benefit.benefit_code join salary ON job.salary_id = salary.salary_id join department ON job.dep_id = department.dep_id join payment ON employee.employee_id = payment.employee_id where employee.employee_id = 15345; 
Select * from payment; 
select benefit_code from job where job_id = 4; 
select benefit_code from job where job_id = 4; 
BEGIN TRANSACTION; 
INSERT INTO employee VALUES (144517, 'Ant','Ciocco','08301999','bruh@test.com','911','No',4); 
INSERT INTO payment VALUES (144517,0,0,0,0,0.153,0,0); 
COMMIT TRANSACTION; 
select employee.*, benefit.* from employee join job ON employee.job_id = job.job_id join benefit ON job.benefit_code = benefit.benefit_code join salary ON job.salary_id = salary.salary_id join department ON job.dep_id = department.dep_id join payment ON employee.employee_id = payment.employee_id where employee.employee_id = 144517; 
SELECT * from employee where employee_id = 144517; 
select benefit_code from job where job_id = 9; 
select benefit_code from job where job_id = 9; 
SELECT * from employee where employee_id = 144517; 
SELECT * from employee where employee_id = 144517; 
SELECT * from employee where employee_id = 144517; 
select benefit_code from job where job_id = 8; 
select benefit_code from job where job_id = 8; 
select employee.*, benefit.* from employee join job ON employee.job_id = job.job_id join benefit ON job.benefit_code = benefit.benefit_code join salary ON job.salary_id = salary.salary_id join department ON job.dep_id = department.dep_id join payment ON employee.employee_id = payment.employee_id where employee.employee_id = 144517; 
select benefit_code from job where job_id = 6; 
select benefit_code from job where job_id = 6; 
select employee.*, benefit.* from employee join job ON employee.job_id = job.job_id join benefit ON job.benefit_code = benefit.benefit_code join salary ON job.salary_id = salary.salary_id join department ON job.dep_id = department.dep_id join payment ON employee.employee_id = payment.employee_id where employee.employee_id = 144517; 
select benefit_code from job where job_id = 15; 
select benefit_code from job where job_id = 15; 
select employee.*, benefit.* from employee join job ON employee.job_id = job.job_id join benefit ON job.benefit_code = benefit.benefit_code join salary ON job.salary_id = salary.salary_id join department ON job.dep_id = department.dep_id join payment ON employee.employee_id = payment.employee_id where employee.employee_id = 144517; 
select benefit_code from job where job_id = 8; 
select benefit_code from job where job_id = 8; 
