Select * from employee 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 0; 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 1; 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 2; 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 3; 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 4; 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 5; 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 6; 
select * from employee join job ON employee.job_id = job.job_id where dep_id = 7; 
Select * from payment; 
Select * from employee; 
Select * from job; 
Select * from salary; 
Select * from department; 
Select * from benefit; 
select employee.*, payment.* from employee join job ON employee.job_id = job.job_id join benefit ON job.benefit_code = benefit.benefit_code join salary ON job.salary_id = salary.salary_id join department ON job.dep_id = department.dep_id join payment ON employee.employee_id = payment.employee_id where employee.employee_id = 41959; 
SELECT * from employee where employee_id = 41959;
select employee.*, job.* from employee join job ON employee.job_id = job.job_id join benefit ON job.benefit_code = benefit.benefit_code join salary ON job.salary_id = salary.salary_id join department ON job.dep_id = department.dep_id join payment ON employee.employee_id = payment.employee_id where employee.employee_id = 41959; 
select employee.*, salary.* from employee join job ON employee.job_id = job.job_id join benefit ON job.benefit_code = benefit.benefit_code join salary ON job.salary_id = salary.salary_id join department ON job.dep_id = department.dep_id join payment ON employee.employee_id = payment.employee_id where employee.employee_id = 41959; 
select employee.*, department.* from employee join job ON employee.job_id = job.job_id join benefit ON job.benefit_code = benefit.benefit_code join salary ON job.salary_id = salary.salary_id join department ON job.dep_id = department.dep_id join payment ON employee.employee_id = payment.employee_id where employee.employee_id = 41959; 
select employee.*, benefit.* from employee join job ON employee.job_id = job.job_id join benefit ON job.benefit_code = benefit.benefit_code join salary ON job.salary_id = salary.salary_id join department ON job.dep_id = department.dep_id join payment ON employee.employee_id = payment.employee_id where employee.employee_id = 41959; 
select benefit_code from job where job_id = 6; 
select benefit_code from job where job_id = 6; 
BEGIN TRANSACTION; 
INSERT INTO employee VALUES (422220, 'Anthony','Ciocco','08-30-1999','test@gmail.com','8325314100','11720 Haben St',6); 
INSERT INTO payment VALUES (422220,2,0,0,0,0.153,0,0); 
COMMIT TRANSACTION; 
SELECT * from employee where employee_id = 422220; 
SELECT * from employee where employee_id = 42222; 
SELECT * from employee where employee_id = 422224; 
SELECT * from employee where employee_id = 422223; 
SELECT * from employee where employee_id = 422223; 
SELECT * from employee where employee_id = 422223; 
SELECT * from employee where employee_id = 422223; 
SELECT * from employee where employee_id = 422222; 
Select * from employee; 
select benefit_code from job where job_id = 3; 
select benefit_code from job where job_id = 3; 
BEGIN TRANSACTION; 
INSERT INTO employee VALUES (00000, 'University','Houston','0000-00-00','uh@gmail.com','0000000000','4800 Calhoun Road',3); 
INSERT INTO payment VALUES (00000,0,0,0,0,0.153,0,0); 
COMMIT TRANSACTION; 
Select * from employee; 
SELECT * from employee where employee_id = 0; 
Select * from employee; 
Select * from employee; 
SELECT * from employee where employee_id = 0; 
SELECT * from employee where employee_id = 00000; 
SELECT * from employee where employee_id = 00000; 
Select * from payment; 
Select * from employee; 
SELECT * from employee where employee_id = 00000;
SELECT * from employee where employee_id = 00000;
SELECT * from employee where employee_id = 00000;
SELECT * from employee where employee_id = 00000;
SELECT * from employee where employee_id = 00000;
SELECT * from employee where employee_id = 0; 
Select * from employee; 
